global:
  name: train-abinet
  phase: train
  stage: train-super
  workdir: train_abinet_nondegraded
  seed: ~
 
dataset:
  train: {
    roots: ['/ssd_scratch/cvit/rafaelgetto/dataset/non_degraded/coco_text_and_art/train/real/train'],
    batch_size: 64
  }
  test: {
    roots: ['/ssd_scratch/cvit/rafaelgetto/dataset/non_degraded/coco_text_and_art/val'],
    batch_size: 64
  }
  data_aug: True
  multiscales: False
  num_workers: 14

training:
  epochs: 10
  show_iters: 1600
  eval_iters: 15000
  save_iters: 15000

optimizer:
  type: Adam
  true_wd: False
  wd: 0.0
  bn_wd: False
  clip_grad: 20
  lr: 0.0001
  args: {
    betas: !!python/tuple [0.9, 0.999], # for default Adam 
  }
  scheduler: {
    periods: [6, 4],
    gamma: 0.1,
  }

model:
  name: 'modules.model_abinet_iter.ABINetIterModel'
  iter_size: 3
  ensemble: ''
  use_vision: False
  vision: {
    checkpoint: workdir/pretrain-vision-model/best-pretrain-vision-model.pth,
    loss_weight: 1.,
    attention: 'position',
    backbone: 'transformer',
    backbone_ln: 3,
  }
  language: {
    checkpoint:  workdir/pretrain-language-model/pretrain-language-model.pth,
    num_layers: 4,
    loss_weight: 1.,
    detach: True,
    use_self_attn: False
  }
  alignment: {
    loss_weight: 1.,
  }
